### ISSUE TITLE
When dropping a JSON secret type, content is stringified

### ISSUE THREAD

**Issue by jacobwaller** [dallen4/deadrop#31]
When attempting to drop a JSON Doc as a secret, ex:
![Screenshot 2023-03-14 at 4 21 12 PM](https://user-images.githubusercontent.com/5910144/225139059-cb4615ae-8480-4fe5-8f5c-612a342cd9ed.png)

deadrop returns a stringified version of what looks like a wrapper object instead of the desired content:
`{"content":"{\n  \"foo\": \"bar\"\n}"}`

**Comment by dallen4** [comment]
fixed in #33
