### ISSUE TITLE
When selecting a JSON object type, but providing a non-parseable input, the "confirm payload" button is not disabled

### ISSUE THREAD

**Issue by jacobwaller** [dallen4/deadrop#32]
![Screenshot 2023-03-14 at 4 24 08 PM](https://user-images.githubusercontent.com/5910144/225139549-f3aad72a-61b9-4012-8e0c-01d3962e2631.png)

Response from deadrop: `{"content":"did nieky handle wacky inputs?"}`

**Comment by dallen4** [comment]
fixed in #33
